import {
	CommonBar,
} from './bar'

import {
	Assist,
	Currency,
	Date,
	Format,
	LinkBar,
	LinkerRadio,
	List,
	Logical,
	Plain,
	Radio,
	Styler,
	Tabular,
} from './cell'

import {
	PlaceHolder,
} from './empty'

import {
	ErrorPage,
} from './error'

import {
	AssistLabel,
	AsyncBox,
	CalculateDater,
	CheckBox,
	ColorPicker,
	CommonLabel,
	CounterBox,
	CurrencyBox,
	CurrencyLabel,
	DateLabel,
	DatePicker,
	DistinctSelector,
	DurationBox,
	FileBox,
	FilterSelector,
	FixedLabel,
	Hidden,
	LinkerBox,
	LinkerLabel,
	ListSelector,
	LoaderDrop,
	LoaderHidden,
	LogicalBox,
	LogicalLabel,
	MatchFilter,
	MultiText,
	NumberRanger,
	OrderedBox,
	PasswordBox,
	PositiveBox,
	RemoteCombo,
	StateLabel,
	StaticDrop,
	TabularDrop,
	TabularLabel,
	TabularSelector,
	TextBox,
	TextBoxArray,
	TreeSelector,
	ViewButton,
} from './field'

import {
	CommonForm,
	CriteriaForm,
	FieldSetForm,
	LoginForm,
	PertainForm,
	StateForm,
} from './form'

import {
	LoginHeader,
} from './header'

import {
	CubeHolder,
	DivideHolder,
	ListHolder,
	MessageHolder,
	SingleFormHolder,
	TabListHolder,
} from './holder'

import {
	Logo,
	OrderContainer,
	RoomCounter,
	RoomDetail,
	RoomNumberBox,
	RoomRowSelector,
	RoomStatusCalendar,
	RoomStatusIcons,
	RoomStatusList,
	RoomStatusReport,
	RoomUseReport,
	RoomViewer,
	TentStatusPage,
} from './hotel'

import {
	FlexList,
	TriplexList,
} from './list'

import {
	PageLoader,
} from './loader'

import {
	CommonButton,
	LinkButton,
	MenuButton,
	SelectButton,
	TackButton,
} from './op'

import {
	FlatTemplate,
	LoginTemplate,
} from './template'

export default {
	"$UCA$.bar.CommonBar":CommonBar,
	"$UCA$.cell.Assist":Assist,
	"$UCA$.cell.Currency":Currency,
	"$UCA$.cell.Date":Date,
	"$UCA$.cell.Format":Format,
	"$UCA$.cell.LinkBar":LinkBar,
	"$UCA$.cell.LinkerRadio":LinkerRadio,
	"$UCA$.cell.List":List,
	"$UCA$.cell.Logical":Logical,
	"$UCA$.cell.Plain":Plain,
	"$UCA$.cell.Radio":Radio,
	"$UCA$.cell.Styler":Styler,
	"$UCA$.cell.Tabular":Tabular,
	"$UCA$.empty.PlaceHolder":PlaceHolder,
	"$UCA$.error.ErrorPage":ErrorPage,
	"$UCA$.field.AssistLabel":AssistLabel,
	"$UCA$.field.AsyncBox":AsyncBox,
	"$UCA$.field.CalculateDater":CalculateDater,
	"$UCA$.field.CheckBox":CheckBox,
	"$UCA$.field.ColorPicker":ColorPicker,
	"$UCA$.field.CommonLabel":CommonLabel,
	"$UCA$.field.CounterBox":CounterBox,
	"$UCA$.field.CurrencyBox":CurrencyBox,
	"$UCA$.field.CurrencyLabel":CurrencyLabel,
	"$UCA$.field.DateLabel":DateLabel,
	"$UCA$.field.DatePicker":DatePicker,
	"$UCA$.field.DistinctSelector":DistinctSelector,
	"$UCA$.field.DurationBox":DurationBox,
	"$UCA$.field.FileBox":FileBox,
	"$UCA$.field.FilterSelector":FilterSelector,
	"$UCA$.field.FixedLabel":FixedLabel,
	"$UCA$.field.Hidden":Hidden,
	"$UCA$.field.LinkerBox":LinkerBox,
	"$UCA$.field.LinkerLabel":LinkerLabel,
	"$UCA$.field.ListSelector":ListSelector,
	"$UCA$.field.LoaderDrop":LoaderDrop,
	"$UCA$.field.LoaderHidden":LoaderHidden,
	"$UCA$.field.LogicalBox":LogicalBox,
	"$UCA$.field.LogicalLabel":LogicalLabel,
	"$UCA$.field.MatchFilter":MatchFilter,
	"$UCA$.field.MultiText":MultiText,
	"$UCA$.field.NumberRanger":NumberRanger,
	"$UCA$.field.OrderedBox":OrderedBox,
	"$UCA$.field.PasswordBox":PasswordBox,
	"$UCA$.field.PositiveBox":PositiveBox,
	"$UCA$.field.RemoteCombo":RemoteCombo,
	"$UCA$.field.StateLabel":StateLabel,
	"$UCA$.field.StaticDrop":StaticDrop,
	"$UCA$.field.TabularDrop":TabularDrop,
	"$UCA$.field.TabularLabel":TabularLabel,
	"$UCA$.field.TabularSelector":TabularSelector,
	"$UCA$.field.TextBox":TextBox,
	"$UCA$.field.TextBoxArray":TextBoxArray,
	"$UCA$.field.TreeSelector":TreeSelector,
	"$UCA$.field.ViewButton":ViewButton,
	"$UCA$.form.CommonForm":CommonForm,
	"$UCA$.form.CriteriaForm":CriteriaForm,
	"$UCA$.form.FieldSetForm":FieldSetForm,
	"$UCA$.form.LoginForm":LoginForm,
	"$UCA$.form.PertainForm":PertainForm,
	"$UCA$.form.StateForm":StateForm,
	"$UCA$.header.LoginHeader":LoginHeader,
	"$UCA$.holder.CubeHolder":CubeHolder,
	"$UCA$.holder.DivideHolder":DivideHolder,
	"$UCA$.holder.ListHolder":ListHolder,
	"$UCA$.holder.MessageHolder":MessageHolder,
	"$UCA$.holder.SingleFormHolder":SingleFormHolder,
	"$UCA$.holder.TabListHolder":TabListHolder,
	"$UCA$.hotel.Logo":Logo,
	"$UCA$.hotel.OrderContainer":OrderContainer,
	"$UCA$.hotel.RoomCounter":RoomCounter,
	"$UCA$.hotel.RoomDetail":RoomDetail,
	"$UCA$.hotel.RoomNumberBox":RoomNumberBox,
	"$UCA$.hotel.RoomRowSelector":RoomRowSelector,
	"$UCA$.hotel.RoomStatusCalendar":RoomStatusCalendar,
	"$UCA$.hotel.RoomStatusIcons":RoomStatusIcons,
	"$UCA$.hotel.RoomStatusList":RoomStatusList,
	"$UCA$.hotel.RoomStatusReport":RoomStatusReport,
	"$UCA$.hotel.RoomUseReport":RoomUseReport,
	"$UCA$.hotel.RoomViewer":RoomViewer,
	"$UCA$.hotel.TentStatusPage":TentStatusPage,
	"$UCA$.list.FlexList":FlexList,
	"$UCA$.list.TriplexList":TriplexList,
	"$UCA$.loader.PageLoader":PageLoader,
	"$UCA$.op.CommonButton":CommonButton,
	"$UCA$.op.LinkButton":LinkButton,
	"$UCA$.op.MenuButton":MenuButton,
	"$UCA$.op.SelectButton":SelectButton,
	"$UCA$.op.TackButton":TackButton,
	"$UCA$.template.FlatTemplate":FlatTemplate,
	"$UCA$.template.LoginTemplate":LoginTemplate,
}