export default {
  // 加载Module配置
  SUCCESS_MOD_INIT: '$$RTV/SUCCESS/MOD_INIT',
  SUCCESS_MOD_START: '$$RTV/SUCCESS/MOD_START',
  // 重新加载数据
  SUCCESS_DATA_RELOAD: '$$RTV/SUCCESS/DATA_RELOAD',
  // 加载App配置
  SUCCESS_APP_INIT: '$$RTV/SUCCESS/APP_INIT',
  SUCCESS_APP_START: '$$RTV/SUCCESS/APP_START',
  SUCCESS_APP_DOWNLOAD: '$$RTV/SUCCESS/APP_DOWNLOAD_START',

  // 加载App数据
  SUCCESS_ARBOR_DATA: '$$RTV/SUCCESS/ARBOR_DATA',
  SUCCESS_ARBOR_TPL: '$$RTV/SUCCESS/ARBOR_TPL',

  // 加载Module数据
  SUCCESS_GOONEY_DATA: '$$RTV/SUCCESS/GOONEY_DATA',
  SUCCESS_GOONEY_CLEAN_DATA: '$$RTV/SUCCESS/GOONEY_CLEAN_DATA',

  // 多个Promise的数据加载
  SUCCESS_FANTOM_DATA: '$$RTV/SUCCESS/FANTOM_DATA',
  SUCCESS_FANTOM_CLEAN_DATA: '$$RTV/SUCCESS/FANTOM_CLEAN_DATA',

  // UI相关事件
  SUCCESS_UI_TAB_MOVING: `$$RTV/SUCCESS/UI_TAB_MOVING`,
  SUCCESS_UI_TAB_SELECT: `$$RTV/SUCCESS/UI_TAB_SELECT`,
  SUCCESS_UI_TAB_REMOVING: `$$RTV/SUCCESS/UI_TAB_REMOVING`,
  SUCCESS_UI_TAB_DYNAMIC: `$$RTV/SUCCESS/UI_TAB_DYNAMIC`,
  SUCCESS_UI_TAB_HIT: `$$RTV/SUCCESS/UI_TAB_HIT`,

  // Pager相关事件
  SUCCESS_UI_PAGER_INDEX: `$$RTV/SUCCESS/UI_PAGER_INDEX`,
  SUCCESS_UI_PAGER_SIZE: `$$RTV/SUCCESS/UI_PAGER_SIZE`,
  SUCCESS_UI_PAGER_SORT: `$$RTV/SUCCESS/UI_PAGER_SORT`,
  SUCCESS_UI_PAGER_RELOAD: `$$RTV/SUCCESS/UI_PAGER_RELOAD`,

  // 选择相关事件
  SUCCESS_UI_SELECTED_ROW: `$$RTV/SUCCESS/UI_SELECTED_ROW`,
  // Form相关事件
  SUCCESS_UI_FORM_INIT: `$$RTV/SUCCESS/UI_FORM_INIT`,
  SUCCESS_UI_FORM_ETAT: `$$RTV/SUCCESS/UI_FORM_ETAT`,
  SUCCESS_UI_FORM_CLEAN: `$$RTV/SUCCESS/UI_FORM_CLEAN`,
  SUCCESS_UI_FORM_CRITERIA: `$$RTV/SUCCESS/UI_FORM_CRITERIA`,
  SUCCESS_UI_ARRAY_ADD_ITEM: `$$RTV/SUCCESS/UI_ARRAY_ADDITEM`,

  // Refresh HASH
  SUCCESS_CONTROL_HASH: `$$RTV/SUCCESS/CONTROL_HASH`,
  SUCCESS_UI_ROW_REFRESH: `$$RTV/SUCCESS/UI_ROW_REFRESH`,

  // Menu
  SUCCESS_UI_MENU_START: `$$RTV/SUCCESS/UI_MENU_START`,
  SUCCESS_UI_MENU_END: `$$RTV/SUCCESS/UI_MENU_END`,

  // 登录成功
  SUCCESS_ACT_LOGIN: '$$RTV/SUCCESS/ACT_LOGIN',
  SUCCESS_ACT_FORM: '$$RTV/SUCCESS/ACT_FORM'
}
